---
- name: Create a YUM repository in target servers
  hosts: db02
  gather_facts: no
  become: yes
  tasks:
    - name: create a mysql yum repository in DB servers
      yum_repository:
        name: mysql80-community
        description: MySQL 8.0 YUM Repo
        baseurl: http://repo.mysql.com/yum/mysql-8.0-community/el/8/x86_64/
        gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
        gpgcheck: yes
        enabled: yes
    - name: Disable mysql default module
      command: yum module disable mysql -y
